sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      env: COMPILER=clang++
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7


before_script:
 - export CXX=$COMPILER
 - $CXX --version
 - tools/linux_x64/premake5 --file=tests/premake5.lua gmake

script:
 - make -C tests/build/gmake config=release
 - tests/bin/gmake/release/nod_tests